# coding: utf-8
# Baseline generated by sqlacodegen mysql://de_user:de_pass@localhost/de_scrape

from sqlalchemy import BigInteger, Column, Date, DateTime, Enum, ForeignKey, Index, Boolean
from sqlalchemy import Float, Integer, Numeric, SmallInteger, String, Table, Text, Time
from sqlalchemy import desc, distinct, text, func


#from sqlalchemy.ext.declarative import declarative_base

from sqlalchemy.orm import relationship, backref, column_property

from sqlalchemy.ext.hybrid import hybrid_property

from flask_security import UserMixin, RoleMixin

import datetime


from de_scrape import db


#Base = declarative_base()
#metadata = Base.metadata





class Role(db.Model, RoleMixin):
    __tablename__ = 'login_role'
    id = Column(Integer(), primary_key=True)
    name = Column(String(80), unique=True)
    description = Column(String(255))

    def __repr__(self):
        return "<Role(name='%s')>" % (
                                self.name)


# Define models
user_role = Table(
    'login_user_role', db.metadata,
    Column('user_id', Integer, ForeignKey('login_user.id'), primary_key=True),
    Column('role_id', Integer, ForeignKey('login_role.id'), primary_key=True))



# Differnece between Role and Group is that roles allow/deny access at the view layer while
# groups determine what content is seen and shared between users
"""

class Group(db.Model):
    id = Column(Integer(), primary_key=True)
    name = Column(String(80), unique=True)
    description = Column(String(255))

    def __repr__(self):
        return "<Group(name='%s')>" % (
                                self.name)
"""


class User(db.Model, UserMixin):
    __tablename__ = 'login_user'
    id = Column(Integer, primary_key=True)

    username = Column(String(255), unique=True)
    email = Column(String(255), unique=True)
    password = Column(String(255))
    active = Column('active', Boolean())
    #confirmed_at = Column(DateTime())

    last_login_at = Column(DateTime())
    current_login_at = Column(DateTime())
    last_login_ip = Column(String(16))
    current_login_ip = Column(String(16))
    login_count = Column(Integer)

    roles = relationship('Role', secondary=user_role,
                            backref=backref('users'))

    """
    groups = relationship('Group', secondary=groups_users,
                            backref=backref('users'))
    """

    def __repr__(self):
        return "<User(username='%s')>" % (
                                self.username)


    def is_active(self):
        return self.active







class DelinquentTaxpayer(db.Model):
    __tablename__ = 'delinquent_taxpayers'

    id = Column(Integer, primary_key=True)
    release_date = Column(Date, nullable=False)
    name = Column(String(128), nullable=False)
    amount = Column(Integer, nullable=False)
    address = Column(String(128), nullable=False)
    city = Column(String(64), nullable=False)
    state = Column(String(16), nullable=False)
    zipcode = Column(Integer, nullable=False)

    def __repr__(self):
        return "<DelinquentTaxpayer(name='%s')>" % (self.name)









class State(db.Model):
    __tablename__ = 'states'

    id = Column(Integer, primary_key=True)
    abbreviation = Column(String(2))
    abbr_lower = Column(String(2))
    state = Column(Text)



def return_candidate_filing_from_name_office(full_name, office):

    try:

        return_candidate_filing_from_name_office = CandidateFiling.query\
            .filter(CandidateFiling.full_name == full_name)\
            .filter(CandidateFiling.office == office)\
            .one()

    except Exception as e:

        return False

    return return_candidate_filing_from_name_office


def check_candidate_filing_exists_from_name_office(full_name, office):

    candidate = return_candidate_filing_from_name_office(full_name, office)

    if candidate is False:
        return False

    return True


class CandidateFiling(db.Model):
    __tablename__ = 'candidate_filing'

    id = Column(Integer, primary_key=True)

    in_general = Column(Integer, nullable=False, server_default=text("'0'"))

    candidate_id = Column(Integer, nullable=False, server_default=text("'0'"), index=True)

    full_name = Column(String(255), nullable=False)
    office = Column(String(128), nullable=False)
    county = Column(String(2), nullable=False)
    party = Column(String(32), nullable=False)
    address = Column(String(255), nullable=False)
    mail_address = Column(String(255), nullable=False)
    email = Column(String(128), nullable=False)
    url = Column(String(128), nullable=False)
    phone = Column(String(20), nullable=False)
    date_filed = Column(DateTime)
    date_found = Column(DateTime)
    page_found = Column(String(16), nullable=False)


    def __repr__(self):
        return "<CandidateFiling(full_name='%s')>" % (self.full_name)


class TestUsAddressCleaner(db.Model):
    __tablename__ = 'test_us_address_cleaner'

    id = Column(Integer, primary_key=True)
    AddressNumber = Column(String(128), server_default=text(""), nullable=False)
    StreetNamePreDirectional = Column(String(128), server_default=text(""), nullable=False)

    StreetName = Column(String(128), server_default=text(""), nullable=False)
    StreetNamePostType = Column(String(128), server_default=text(""), nullable=False)
    PlaceName = Column(String(128), server_default=text(""), nullable=False)
    StateName = Column(String(128), server_default=text(""), nullable=False)
    ZipCode = Column(String(128), server_default=text(""), nullable=False)


